/**
 * ApplicationGenerator
 *
 * Generates complete standalone application from application definition
 */

const fs = require('fs').promises;
const path = require('path');

class ApplicationGenerator {
  constructor(application) {
    this.application = application;
    this.outputPath = path.join(__dirname, '../../generated-apps', application.id);
  }

  async generate() {
    console.log('[ApplicationGenerator] Generating scaffold for:', this.application.name);

    try {
      // Create output directory
      await fs.mkdir(this.outputPath, { recursive: true });

      const files = [];

      // Generate package.json
      files.push(await this.generatePackageJson());

      // Generate resources
      files.push(await this.generateResources());

      // Generate README
      files.push(await this.generateReadme());

      console.log(`[ApplicationGenerator] Generated ${files.length} files at ${this.outputPath}`);

      return {
        path: this.outputPath,
        files
      };
    } catch (error) {
      console.error('[ApplicationGenerator] Failed to generate:', error);
      throw error;
    }
  }

  async generatePackageJson() {
    const packageJson = {
      name: this.application.id,
      version: this.application.version || '1.0.0',
      description: this.application.description,
      main: 'src/server.js',
      scripts: {
        start: 'node src/server.js',
        dev: 'nodemon src/server.js'
      },
      dependencies: {
        express: '^4.18.2',
        cors: '^2.8.5',
        'body-parser': '^1.20.2',
        dotenv: '^16.0.3'
      },
      devDependencies: {
        nodemon: '^2.0.22'
      }
    };

    const filePath = path.join(this.outputPath, 'package.json');
    await fs.writeFile(filePath, JSON.stringify(packageJson, null, 2));
    return 'package.json';
  }

  async generateResources() {
    const resourcesDir = path.join(this.outputPath, 'src/resources');
    await fs.mkdir(resourcesDir, { recursive: true });

    // Write all resources as JSON files
    const resources = this.application.resources;

    if (resources.workflows) {
      await fs.writeFile(
        path.join(resourcesDir, 'workflows.json'),
        JSON.stringify(resources.workflows, null, 2)
      );
    }

    if (resources.dataModels) {
      await fs.writeFile(
        path.join(resourcesDir, 'dataModels.json'),
        JSON.stringify(resources.dataModels, null, 2)
      );
    }

    if (resources.forms) {
      await fs.writeFile(
        path.join(resourcesDir, 'forms.json'),
        JSON.stringify(resources.forms, null, 2)
      );
    }

    if (resources.pages) {
      await fs.writeFile(
        path.join(resourcesDir, 'pages.json'),
        JSON.stringify(resources.pages, null, 2)
      );
    }

    return 'resources';
  }

  async generateReadme() {
    const readme = `# ${this.application.name}

${this.application.description}

## Generated Application

This application was generated by the Workflow Platform.

### Resources
- Workflows: ${this.application.stats.workflowCount}
- Data Models: ${this.application.stats.modelCount}
- Forms: ${this.application.stats.formCount}
- Pages: ${this.application.stats.pageCount}

### Running the Application

\`\`\`bash
npm install
npm start
\`\`\`

Application will run on port ${this.application.runtime.port || 4000}.

### Configuration

See \`.env\` file for configuration options.

---

Generated: ${new Date().toISOString()}
Platform Version: 1.0.0
`;

    const filePath = path.join(this.outputPath, 'README.md');
    await fs.writeFile(filePath, readme);
    return 'README.md';
  }
}

module.exports = ApplicationGenerator;
