import React, { useState } from 'react';
import './MobileScreensPanel.css';
import { useWorkflow } from '../../context/WorkflowContext';
import { Smartphone, Monitor, Tablet } from 'lucide-react';

const MobileScreensPanel = () => {
  const { currentWorkflow } = useWorkflow();
  const [selectedScreen, setSelectedScreen] = useState(0);
  const [deviceFrame, setDeviceFrame] = useState('ios'); // ios, android, tablet

  const mobileUI = currentWorkflow?.mobileUI;
  const screens = mobileUI?.screens || [];

  if (screens.length === 0) {
    return (
      <div className="mobile-screens-panel">
        <div className="panel-header">
          <h2>Mobile Screens</h2>
          <p className="panel-subtitle">Mobile UI generated by AI agents</p>
        </div>
        <div className="empty-state">
          <Smartphone size={64} className="empty-icon" />
          <h3>No Mobile Screens Yet</h3>
          <p>
            Generate a workflow with multi-agent or MoE mode enabled to see mobile screens.
          </p>
          <p className="hint">
            Mobile screens are automatically generated for each workflow step.
          </p>
        </div>
      </div>
    );
  }

  const currentScreen = screens[selectedScreen];

  const renderDeviceFrameSelector = () => (
    <div className="device-selector">
      <button
        className={`device-btn ${deviceFrame === 'ios' ? 'active' : ''}`}
        onClick={() => setDeviceFrame('ios')}
        title="iPhone"
      >
        <Smartphone size={16} />
        <span>iOS</span>
      </button>
      <button
        className={`device-btn ${deviceFrame === 'android' ? 'active' : ''}`}
        onClick={() => setDeviceFrame('android')}
        title="Android"
      >
        <Monitor size={16} />
        <span>Android</span>
      </button>
      <button
        className={`device-btn ${deviceFrame === 'tablet' ? 'active' : ''}`}
        onClick={() => setDeviceFrame('tablet')}
        title="Tablet"
      >
        <Tablet size={16} />
        <span>Tablet</span>
      </button>
    </div>
  );

  const renderScreensList = () => (
    <div className="screens-list">
      <h3>Screens ({screens.length})</h3>
      <div className="screens-grid">
        {screens.map((screen, index) => (
          <button
            key={screen.id || index}
            className={`screen-card ${selectedScreen === index ? 'active' : ''}`}
            onClick={() => setSelectedScreen(index)}
          >
            <div className="screen-preview-mini">
              <Smartphone size={24} />
            </div>
            <div className="screen-info">
              <div className="screen-name">{screen.name || `Screen ${index + 1}`}</div>
              <div className="screen-type">{screen.type || 'unknown'}</div>
            </div>
          </button>
        ))}
      </div>
    </div>
  );

  const renderComponentTree = (components, level = 0) => {
    if (!components || components.length === 0) return null;

    return (
      <ul className={`component-tree level-${level}`}>
        {components.map((comp, idx) => (
          <li key={idx} className="component-item">
            <div className="component-info">
              <span className="component-type">{comp.type}</span>
              {comp.props?.title && (
                <span className="component-label">: {comp.props.title}</span>
              )}
              {comp.props?.label && (
                <span className="component-label">: {comp.props.label}</span>
              )}
            </div>
            {comp.children && renderComponentTree(comp.children, level + 1)}
          </li>
        ))}
      </ul>
    );
  };

  const renderScreenPreview = () => {
    if (!currentScreen) return null;

    const frameClass = `device-frame ${deviceFrame}`;

    return (
      <div className="screen-preview-container">
        <div className="screen-header">
          <h3>{currentScreen.name || 'Screen'}</h3>
          <div className="screen-meta">
            <span className="badge">{currentScreen.type}</span>
            {currentScreen.platform && (
              <span className="badge">{currentScreen.platform}</span>
            )}
          </div>
        </div>

        <div className={frameClass}>
          <div className="device-screen">
            <div className="screen-content">
              <div className="screen-details">
                <h4>Screen Structure</h4>
                {currentScreen.components && renderComponentTree(currentScreen.components)}
              </div>

              {currentScreen.workflowNodeId && (
                <div className="screen-metadata">
                  <strong>Linked to:</strong> Node {currentScreen.workflowNodeId}
                </div>
              )}

              {currentScreen.formId && (
                <div className="screen-metadata">
                  <strong>Form:</strong> {currentScreen.formId}
                </div>
              )}

              <div className="screen-json">
                <h4>Screen Definition</h4>
                <pre>{JSON.stringify(currentScreen, null, 2)}</pre>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div className="mobile-screens-panel">
      <div className="panel-header">
        <div>
          <h2>Mobile Screens</h2>
          <p className="panel-subtitle">
            {screens.length} screen{screens.length !== 1 ? 's' : ''} generated
          </p>
        </div>
        {renderDeviceFrameSelector()}
      </div>

      <div className="panel-content">
        <div className="panel-sidebar">
          {renderScreensList()}
        </div>
        <div className="panel-main">
          {renderScreenPreview()}
        </div>
      </div>
    </div>
  );
};

export default MobileScreensPanel;
