import React, { useState, useEffect } from 'react';
import './MobileScreensPanel.css';
import { useWorkflow } from '../../context/WorkflowContext';
import { Smartphone, Monitor, Tablet, Network, QrCode, Copy, Check, ExternalLink } from 'lucide-react';
import MobileFlowCanvas from '../MobileFlow/MobileFlowCanvas';

// Simple QR Code component using SVG
const QRCodeDisplay = ({ value, size = 150 }) => {
  // Simple QR code pattern generator (for demo - in production use qrcode.react)
  const moduleCount = 21;
  const moduleSize = size / moduleCount;

  // Generate a simple pattern based on the value hash
  const generatePattern = (val) => {
    const pattern = [];
    let hash = 0;
    for (let i = 0; i < val.length; i++) {
      hash = ((hash << 5) - hash) + val.charCodeAt(i);
      hash = hash & hash;
    }

    // Create a pseudo-random pattern based on hash
    for (let row = 0; row < moduleCount; row++) {
      pattern[row] = [];
      for (let col = 0; col < moduleCount; col++) {
        // Always fill finder patterns (corners)
        const isFinderPattern =
          (row < 7 && col < 7) ||
          (row < 7 && col >= moduleCount - 7) ||
          (row >= moduleCount - 7 && col < 7);

        if (isFinderPattern) {
          // Create finder pattern
          const inOuter = row < 7 && col < 7
            ? (row === 0 || row === 6 || col === 0 || col === 6)
            : row < 7 && col >= moduleCount - 7
              ? (row === 0 || row === 6 || col === moduleCount - 7 || col === moduleCount - 1)
              : (row === moduleCount - 7 || row === moduleCount - 1 || col === 0 || col === 6);

          const inInner = row < 7 && col < 7
            ? (row >= 2 && row <= 4 && col >= 2 && col <= 4)
            : row < 7 && col >= moduleCount - 7
              ? (row >= 2 && row <= 4 && col >= moduleCount - 5 && col <= moduleCount - 3)
              : (row >= moduleCount - 5 && row <= moduleCount - 3 && col >= 2 && col <= 4);

          pattern[row][col] = inOuter || inInner;
        } else {
          // Data area - pseudo-random based on hash
          const seed = (hash + row * 31 + col * 17) % 100;
          pattern[row][col] = seed < 45;
        }
      }
    }
    return pattern;
  };

  const pattern = generatePattern(value);

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`}>
      <rect width={size} height={size} fill="white" />
      {pattern.map((row, rowIndex) =>
        row.map((cell, colIndex) =>
          cell ? (
            <rect
              key={`${rowIndex}-${colIndex}`}
              x={colIndex * moduleSize}
              y={rowIndex * moduleSize}
              width={moduleSize}
              height={moduleSize}
              fill="#1a1a1a"
            />
          ) : null
        )
      )}
    </svg>
  );
};

const MobileScreensPanel = () => {
  const { currentWorkflow, currentApplication } = useWorkflow();
  const [selectedScreen, setSelectedScreen] = useState(0);
  const [deviceFrame, setDeviceFrame] = useState('ios'); // ios, android, tablet
  const [viewMode, setViewMode] = useState('preview'); // 'preview', 'flow', or 'expo'
  const [copied, setCopied] = useState(false);
  const [serverIP, setServerIP] = useState('');

  // Get local network IP for Expo connection
  useEffect(() => {
    // Try to get the server URL from environment or use localhost
    const backendUrl = process.env.REACT_APP_API_URL || 'http://localhost:5000';
    setServerIP(backendUrl.replace('http://', '').replace('/api', '').split(':')[0]);
  }, []);

  const mobileUI = currentWorkflow?.mobileUI;
  const screens = mobileUI?.screens || [];
  const appId = currentApplication?.id || currentWorkflow?.applicationId || 'demo_app';

  if (screens.length === 0) {
    return (
      <div className="mobile-screens-panel">
        <div className="panel-header">
          <h2>Mobile Screens</h2>
          <p className="panel-subtitle">Mobile UI generated by AI agents</p>
        </div>
        <div className="empty-state">
          <Smartphone size={64} className="empty-icon" />
          <h3>No Mobile Screens Yet</h3>
          <p>
            Generate a workflow with multi-agent or MoE mode enabled to see mobile screens.
          </p>
          <p className="hint">
            Mobile screens are automatically generated for each workflow step.
          </p>
        </div>
      </div>
    );
  }

  const currentScreen = screens[selectedScreen];

  const renderDeviceFrameSelector = () => (
    <div className="device-selector">
      <button
        className={`device-btn ${deviceFrame === 'ios' ? 'active' : ''}`}
        onClick={() => setDeviceFrame('ios')}
        title="iPhone"
      >
        <Smartphone size={16} />
        <span>iOS</span>
      </button>
      <button
        className={`device-btn ${deviceFrame === 'android' ? 'active' : ''}`}
        onClick={() => setDeviceFrame('android')}
        title="Android"
      >
        <Monitor size={16} />
        <span>Android</span>
      </button>
      <button
        className={`device-btn ${deviceFrame === 'tablet' ? 'active' : ''}`}
        onClick={() => setDeviceFrame('tablet')}
        title="Tablet"
      >
        <Tablet size={16} />
        <span>Tablet</span>
      </button>
    </div>
  );

  const renderScreensList = () => (
    <div className="screens-list">
      <h3>Screens ({screens.length})</h3>
      <div className="screens-grid">
        {screens.map((screen, index) => (
          <button
            key={screen.id || index}
            className={`screen-card ${selectedScreen === index ? 'active' : ''}`}
            onClick={() => setSelectedScreen(index)}
          >
            <div className="screen-preview-mini">
              <Smartphone size={24} />
            </div>
            <div className="screen-info">
              <div className="screen-name">{screen.name || `Screen ${index + 1}`}</div>
              <div className="screen-type">{screen.type || 'unknown'}</div>
            </div>
          </button>
        ))}
      </div>
    </div>
  );

  const renderComponentTree = (components, level = 0) => {
    if (!components || components.length === 0) return null;

    return (
      <ul className={`component-tree level-${level}`}>
        {components.map((comp, idx) => (
          <li key={idx} className="component-item">
            <div className="component-info">
              <span className="component-type">{comp.type}</span>
              {comp.props?.title && (
                <span className="component-label">: {comp.props.title}</span>
              )}
              {comp.props?.label && (
                <span className="component-label">: {comp.props.label}</span>
              )}
            </div>
            {comp.children && renderComponentTree(comp.children, level + 1)}
          </li>
        ))}
      </ul>
    );
  };

  // Visual Component Renderer - renders actual UI preview
  const renderVisualComponent = (component, index = 0) => {
    if (!component) return null;

    const { type, props = {}, children = [], style = {}, layout = {} } = component;

    const commonStyle = {
      padding: layout.padding || 0,
      margin: layout.margin || 0,
      backgroundColor: style.backgroundColor,
      ...style
    };

    switch (type?.toLowerCase()) {
      case 'screen':
      case 'safeareaview':
      case 'scrollview':
        return (
          <div key={index} style={{ ...commonStyle, flex: 1 }}>
            {children.map((child, idx) => renderVisualComponent(child, idx))}
          </div>
        );

      case 'header':
        return (
          <div key={index} style={{
            ...commonStyle,
            padding: '16px',
            backgroundColor: '#3b82f6',
            color: 'white',
            fontWeight: '600',
            fontSize: '18px',
            borderBottom: '1px solid #e5e7eb'
          }}>
            {props.title || props.headerTitle || 'Header'}
          </div>
        );

      case 'card':
      case 'section':
        return (
          <div key={index} style={{
            ...commonStyle,
            padding: '16px',
            margin: '12px 0',
            backgroundColor: '#ffffff',
            borderRadius: '8px',
            border: '1px solid #e5e7eb',
            boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)'
          }}>
            {children.map((child, idx) => renderVisualComponent(child, idx))}
          </div>
        );

      case 'stack':
        return (
          <div key={index} style={{
            ...commonStyle,
            display: 'flex',
            flexDirection: 'column',
            gap: '12px'
          }}>
            {children.map((child, idx) => renderVisualComponent(child, idx))}
          </div>
        );

      case 'row':
        return (
          <div key={index} style={{
            ...commonStyle,
            display: 'flex',
            flexDirection: 'row',
            gap: '12px',
            alignItems: 'center'
          }}>
            {children.map((child, idx) => renderVisualComponent(child, idx))}
          </div>
        );

      case 'heading':
        return (
          <h3 key={index} style={{
            ...commonStyle,
            margin: '16px 0 8px',
            fontSize: '20px',
            fontWeight: '600',
            color: '#111827'
          }}>
            {props.text || props.title || props.children || 'Heading'}
          </h3>
        );

      case 'text':
      case 'label':
        return (
          <p key={index} style={{
            ...commonStyle,
            margin: '4px 0',
            fontSize: '14px',
            color: props.color || '#374151',
            fontWeight: props.bold ? '600' : '400'
          }}>
            {props.text || props.children || props.title || 'Text'}
          </p>
        );

      case 'textinput':
      case 'input':
        return (
          <input
            key={index}
            type="text"
            placeholder={props.placeholder || 'Enter text...'}
            style={{
              ...commonStyle,
              padding: '10px 14px',
              border: '1px solid #d1d5db',
              borderRadius: '6px',
              fontSize: '14px',
              width: '100%',
              boxSizing: 'border-box'
            }}
            disabled
          />
        );

      case 'textarea':
        return (
          <textarea
            key={index}
            placeholder={props.placeholder || 'Enter text...'}
            rows={props.rows || 3}
            style={{
              ...commonStyle,
              padding: '10px 14px',
              border: '1px solid #d1d5db',
              borderRadius: '6px',
              fontSize: '14px',
              width: '100%',
              boxSizing: 'border-box',
              fontFamily: 'inherit',
              resize: 'vertical'
            }}
            disabled
          />
        );

      case 'button':
        return (
          <button key={index} style={{
            ...commonStyle,
            padding: '12px 24px',
            backgroundColor: props.primary ? '#3b82f6' : '#ffffff',
            color: props.primary ? '#ffffff' : '#374151',
            border: props.primary ? 'none' : '1px solid #d1d5db',
            borderRadius: '6px',
            fontSize: '14px',
            fontWeight: '500',
            cursor: 'not-allowed',
            boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)'
          }}>
            {props.title || props.text || props.label || 'Button'}
          </button>
        );

      case 'iconbutton':
      case 'fab':
        return (
          <button key={index} style={{
            ...commonStyle,
            width: '48px',
            height: '48px',
            backgroundColor: '#3b82f6',
            color: '#ffffff',
            border: 'none',
            borderRadius: type === 'fab' ? '50%' : '6px',
            fontSize: '20px',
            cursor: 'not-allowed',
            boxShadow: '0 2px 8px rgba(59, 130, 246, 0.3)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            {props.icon || '+'}
          </button>
        );

      case 'list':
      case 'listitem':
        return (
          <div key={index} style={{
            ...commonStyle,
            padding: '12px 16px',
            backgroundColor: '#ffffff',
            borderBottom: '1px solid #e5e7eb',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between'
          }}>
            <span style={{ fontSize: '14px', color: '#111827' }}>
              {props.title || props.text || 'List Item'}
            </span>
            {props.subtitle && (
              <span style={{ fontSize: '12px', color: '#6b7280' }}>
                {props.subtitle}
              </span>
            )}
          </div>
        );

      case 'badge':
        return (
          <span key={index} style={{
            ...commonStyle,
            display: 'inline-block',
            padding: '4px 10px',
            backgroundColor: props.color || '#3b82f6',
            color: '#ffffff',
            borderRadius: '12px',
            fontSize: '12px',
            fontWeight: '500'
          }}>
            {props.text || props.label || 'Badge'}
          </span>
        );

      case 'divider':
        return (
          <hr key={index} style={{
            ...commonStyle,
            border: 'none',
            borderTop: '1px solid #e5e7eb',
            margin: '16px 0'
          }} />
        );

      case 'image':
        return (
          <div key={index} style={{
            ...commonStyle,
            width: props.width || '100%',
            height: props.height || '200px',
            backgroundColor: '#f3f4f6',
            borderRadius: '8px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#9ca3af',
            fontSize: '14px'
          }}>
            📷 Image Placeholder
          </div>
        );

      case 'switch':
      case 'checkbox':
        return (
          <label key={index} style={{
            ...commonStyle,
            display: 'flex',
            alignItems: 'center',
            gap: '12px',
            fontSize: '14px',
            color: '#374151'
          }}>
            <input
              type="checkbox"
              style={{ width: '20px', height: '20px', accentColor: '#3b82f6' }}
              disabled
            />
            {props.label || props.title || 'Option'}
          </label>
        );

      case 'picker':
      case 'dropdown':
        return (
          <select key={index} style={{
            ...commonStyle,
            padding: '10px 14px',
            border: '1px solid #d1d5db',
            borderRadius: '6px',
            fontSize: '14px',
            width: '100%',
            boxSizing: 'border-box'
          }} disabled>
            <option>{props.placeholder || 'Select an option...'}</option>
          </select>
        );

      case 'searchbar':
        return (
          <input
            key={index}
            type="search"
            placeholder={props.placeholder || 'Search...'}
            style={{
              ...commonStyle,
              padding: '10px 14px 10px 38px',
              border: '1px solid #d1d5db',
              borderRadius: '20px',
              fontSize: '14px',
              width: '100%',
              boxSizing: 'border-box',
              backgroundImage: 'url("data:image/svg+xml,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'16\' height=\'16\' fill=\'%236b7280\' viewBox=\'0 0 16 16\'%3E%3Cpath d=\'M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\'/%3E%3C/svg%3E")',
              backgroundRepeat: 'no-repeat',
              backgroundPosition: '12px center'
            }}
            disabled
          />
        );

      case 'view':
      default:
        if (children && children.length > 0) {
          return (
            <div key={index} style={commonStyle}>
              {children.map((child, idx) => renderVisualComponent(child, idx))}
            </div>
          );
        }
        return null;
    }
  };

  const renderScreenPreview = () => {
    if (!currentScreen) return null;

    const frameClass = `device-frame ${deviceFrame}`;

    return (
      <div className="screen-preview-container">
        <div className="screen-header">
          <h3>{currentScreen.name || 'Screen'}</h3>
          <div className="screen-meta">
            <span className="badge">{currentScreen.type}</span>
            {currentScreen.platform && (
              <span className="badge">{currentScreen.platform}</span>
            )}
          </div>
        </div>

        <div className={frameClass}>
          <div className="device-screen">
            <div className="mobile-ui-preview">
              {/* Render actual visual UI */}
              {currentScreen.navigation?.showHeader && (
                <div style={{
                  padding: '16px',
                  backgroundColor: '#3b82f6',
                  color: 'white',
                  fontWeight: '600',
                  fontSize: '18px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '12px'
                }}>
                  {currentScreen.navigation.showBackButton && <span>‹</span>}
                  <span>{currentScreen.navigation.headerTitle || currentScreen.name}</span>
                </div>
              )}

              <div style={{ padding: '16px', overflowY: 'auto', flex: 1 }}>
                {currentScreen.components && currentScreen.components.map((comp, idx) =>
                  renderVisualComponent(comp, idx)
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Technical Details - Collapsible */}
        <details style={{ marginTop: '24px' }}>
          <summary style={{
            cursor: 'pointer',
            fontWeight: '600',
            fontSize: '14px',
            padding: '12px',
            backgroundColor: '#f9fafb',
            borderRadius: '6px',
            userSelect: 'none'
          }}>
            Technical Details
          </summary>
          <div style={{ padding: '16px', backgroundColor: '#ffffff', borderRadius: '6px', marginTop: '8px' }}>
            <div className="screen-details">
              <h4>Component Structure</h4>
              {currentScreen.components && renderComponentTree(currentScreen.components)}
            </div>

            {currentScreen.workflowNodeId && (
              <div className="screen-metadata">
                <strong>Linked to:</strong> Node {currentScreen.workflowNodeId}
              </div>
            )}

            {currentScreen.formId && (
              <div className="screen-metadata">
                <strong>Form:</strong> {currentScreen.formId}
              </div>
            )}

            <div className="screen-json">
              <h4>Screen Definition</h4>
              <pre>{JSON.stringify(currentScreen, null, 2)}</pre>
            </div>
          </div>
        </details>
      </div>
    );
  };

  // Handle switching back from flow view
  const handleBackFromFlow = () => {
    setViewMode('preview');
  };

  // Copy app connection info to clipboard
  const copyConnectionInfo = () => {
    const connectionInfo = `Server: http://${serverIP}:5000/api\nApp ID: ${appId}`;
    navigator.clipboard.writeText(connectionInfo);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  // Render Expo Go preview section
  const renderExpoPreview = () => {
    const expoUrl = `workflowpp://connect?server=${serverIP}&port=5000&appId=${appId}`;

    return (
      <div className="expo-preview-panel">
        <button
          className="back-btn"
          onClick={() => setViewMode('preview')}
          style={{
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            padding: '8px 16px',
            border: '1px solid #e5e7eb',
            borderRadius: '6px',
            background: '#fff',
            cursor: 'pointer',
            marginBottom: '24px'
          }}
        >
          Back to Preview
        </button>

        <div style={{ textAlign: 'center', maxWidth: '400px', margin: '0 auto' }}>
          <div style={{
            width: '80px',
            height: '80px',
            background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
            borderRadius: '20px',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 24px'
          }}>
            <QrCode size={40} color="#fff" />
          </div>

          <h2 style={{ fontSize: '24px', fontWeight: '600', marginBottom: '8px', color: '#111827' }}>
            Preview on Device
          </h2>
          <p style={{ color: '#6b7280', marginBottom: '32px' }}>
            Connect with Expo Go to preview your app on a real device
          </p>

          {/* QR Code */}
          <div style={{
            background: '#fff',
            padding: '24px',
            borderRadius: '12px',
            border: '1px solid #e5e7eb',
            marginBottom: '24px'
          }}>
            <QRCodeDisplay value={expoUrl} size={180} />
            <p style={{ fontSize: '12px', color: '#9ca3af', marginTop: '16px' }}>
              Scan with Expo Go app
            </p>
          </div>

          {/* Connection Details */}
          <div style={{
            background: '#f9fafb',
            padding: '20px',
            borderRadius: '12px',
            textAlign: 'left',
            marginBottom: '24px'
          }}>
            <h4 style={{ fontSize: '14px', fontWeight: '600', marginBottom: '16px', color: '#374151' }}>
              Manual Connection
            </h4>

            <div style={{ marginBottom: '12px' }}>
              <label style={{ fontSize: '12px', color: '#6b7280', display: 'block', marginBottom: '4px' }}>
                Server URL
              </label>
              <div style={{
                background: '#fff',
                padding: '10px 12px',
                borderRadius: '6px',
                border: '1px solid #e5e7eb',
                fontFamily: 'monospace',
                fontSize: '13px'
              }}>
                http://{serverIP}:5000/api
              </div>
            </div>

            <div style={{ marginBottom: '16px' }}>
              <label style={{ fontSize: '12px', color: '#6b7280', display: 'block', marginBottom: '4px' }}>
                App ID
              </label>
              <div style={{
                background: '#fff',
                padding: '10px 12px',
                borderRadius: '6px',
                border: '1px solid #e5e7eb',
                fontFamily: 'monospace',
                fontSize: '13px'
              }}>
                {appId}
              </div>
            </div>

            <button
              onClick={copyConnectionInfo}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px',
                width: '100%',
                padding: '10px',
                border: '1px solid #e5e7eb',
                borderRadius: '6px',
                background: '#fff',
                cursor: 'pointer',
                fontSize: '14px',
                fontWeight: '500',
                color: copied ? '#16a34a' : '#374151'
              }}
            >
              {copied ? <Check size={16} /> : <Copy size={16} />}
              {copied ? 'Copied!' : 'Copy Connection Info'}
            </button>
          </div>

          {/* Instructions */}
          <div style={{
            background: '#eff6ff',
            padding: '16px',
            borderRadius: '8px',
            textAlign: 'left'
          }}>
            <h4 style={{ fontSize: '14px', fontWeight: '600', marginBottom: '8px', color: '#1e40af' }}>
              Getting Started
            </h4>
            <ol style={{ fontSize: '13px', color: '#3b82f6', paddingLeft: '20px', margin: 0 }}>
              <li style={{ marginBottom: '6px' }}>Install Expo Go on your device</li>
              <li style={{ marginBottom: '6px' }}>Run <code style={{ background: '#dbeafe', padding: '2px 6px', borderRadius: '4px' }}>cd mobile && npx expo start</code></li>
              <li style={{ marginBottom: '6px' }}>Scan QR code or enter connection details</li>
              <li>Your app will load automatically!</li>
            </ol>
          </div>
        </div>
      </div>
    );
  };

  // If in flow view, show the MobileFlowCanvas
  if (viewMode === 'flow') {
    return <MobileFlowCanvas onBack={handleBackFromFlow} />;
  }

  // If in expo view, show the Expo preview panel
  if (viewMode === 'expo') {
    return (
      <div className="mobile-screens-panel">
        <div className="panel-header">
          <div>
            <h2>Mobile Screens</h2>
            <p className="panel-subtitle">Expo Go Preview</p>
          </div>
        </div>
        <div className="panel-content" style={{ justifyContent: 'center', padding: '40px' }}>
          {renderExpoPreview()}
        </div>
      </div>
    );
  }

  return (
    <div className="mobile-screens-panel">
      <div className="panel-header">
        <div>
          <h2>Mobile Screens</h2>
          <p className="panel-subtitle">
            {screens.length} screen{screens.length !== 1 ? 's' : ''} generated
          </p>
        </div>
        <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
          <button
            className="btn-view-flow"
            onClick={() => setViewMode('expo')}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: '6px',
              padding: '8px 16px',
              background: 'linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)',
              color: '#fff',
              border: 'none',
              borderRadius: '6px',
              cursor: 'pointer',
              fontSize: '14px',
              fontWeight: '500'
            }}
          >
            <ExternalLink size={16} />
            Expo Go
          </button>
          <button
            className="btn-view-flow"
            onClick={() => setViewMode('flow')}
          >
            <Network size={18} />
            View Flow
          </button>
          {renderDeviceFrameSelector()}
        </div>
      </div>

      <div className="panel-content">
        <div className="panel-sidebar">
          {renderScreensList()}
        </div>
        <div className="panel-main">
          {renderScreenPreview()}
        </div>
      </div>
    </div>
  );
};

export default MobileScreensPanel;
